logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 124.222.161.233
    port: 5672
    virtual-host: /
    username: momomo
    password: 20040813,ljh.
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息